# Generated by Django 5.2.3 on 2025-06-22 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enquiries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agency_enquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='franchise_enquiries', to=settings.AUTH_USER_MODEL),
        ),
    ]
