# Generated by Django 5.2.3 on 2025-06-27 07:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('package_type', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField()),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Main content for the homepage')),
                ('background_video', models.FileField(blank=True, null=True, upload_to='homepage_videos/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='homepage_images/')),
                ('welcome_title', models.CharField(default='Welcome', max_length=200)),
                ('welcome_subtitle', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(choices=[('umrah_classic', 'Classic Umrah Package'), ('umrah_delux', 'Delux Umrah Package'), ('umrah_luxury', 'Luxury Umrah Package'), ('hajj_classic', 'Classic Hajj Package'), ('hajj_delux', 'Delux Hajj Package'), ('hajj_luxury', 'Luxury Hajj Package'), ('ramadan_early', 'Early Ramadan Package'), ('ramadan_laylat', 'Laylat al-Qadr Package'), ('ramadan_full', 'Full Month Ramadan Package')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='package_images/')),
                ('features', models.TextField(blank=True, help_text='Enter features separated by new lines')),
                ('duration_days', models.IntegerField(default=7)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['package_type'],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('name', models.CharField(help_text='Name/description for this API key', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, help_text='Website URL where this key is used', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Enquiry',
        ),
    ]
