# Generated by Django 5.2.3 on 2025-06-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0003_contactus_homepage_package_apikey_delete_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='package_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
