# Generated by Django 5.2.3 on 2025-06-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0004_alter_contactus_email_alter_contactus_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='currency',
            field=models.CharField(blank=True, default='INR', max_length=10, null=True),
        ),
    ]
