# Generated by Django 5.2.3 on 2025-06-30 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0006_contactus_notes_contactus_processed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='contactus',
            name='api_key',
            field=models.ForeignKey(blank=True, help_text='API key used to submit this contact form', null=True, on_delete=django.db.models.deletion.SET_NULL, to='enquiries.apikey'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='submitted_by_user',
            field=models.ForeignKey(blank=True, help_text='User who owns the API key used for submission', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
