# Generated by Django 5.2.3 on 2026-01-17 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0008_alter_contactus_api_key_alter_contactus_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='package',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_type',
            field=models.CharField(choices=[('umrah_classic', 'Classic Umrah Package'), ('umrah_delux', 'Delux Umrah Package'), ('umrah_luxury', 'Luxury Umrah Package'), ('hajj_classic', 'Classic Hajj Package'), ('hajj_delux', 'Delux Hajj Package'), ('hajj_luxury', 'Luxury Hajj Package'), ('ramadan_early', 'Early Ramadan Package'), ('ramadan_laylat', 'Laylat al-Qadr Package'), ('ramadan_full', 'Full Month Ramadan Package')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together={('user', 'package_type')},
        ),
    ]
