# Generated by Django 5.2.3 on 2025-07-01 09:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HajjUmrahBookingDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_date', models.DateField()),
                ('selected_time', models.TimeField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('business_plan', models.CharField(choices=[('agency', 'Agency ID'), ('franchise', 'Franchises ID'), ('freelancer', 'Freelancer ID')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hajj Umrah Booking Demo',
                'verbose_name_plural': 'Hajj Umrah Booking Demos',
                'db_table': 'hajj_umrah_booking_demo',
            },
        ),
        migrations.CreateModel(
            name='HajjUmrahBookingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('business_plan', models.CharField(choices=[('agency', 'Agency ID'), ('franchise', 'Franchises ID'), ('freelancer', 'Freelancer ID')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hajj Umrah Booking Service',
                'verbose_name_plural': 'Hajj Umrah Booking Services',
                'db_table': 'hajj_umrah_booking_service',
            },
        ),
    ]
