# Generated by Django 5.2.3 on 2025-06-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('package_type', models.CharField(choices=[('classic_hajj', 'Classic Hajj'), ('deluxe_hajj', 'Deluxe Hajj'), ('luxury_hajj', 'Luxury Hajj'), ('classic_umrah', 'Classic Umrah'), ('deluxe_umrah', 'Deluxe Umrah'), ('luxury_umrah', 'Luxury Umrah'), ('ramadan_20_days', 'First 20 Days Ramadan'), ('ramadan_18_days', 'Last 18 Days Ramadan'), ('ramadan_full_month', 'Full Month Ramadan')], max_length=50)),
                ('destination', models.CharField(max_length=255)),
                ('duration_days', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
