# Generated by Django 5.2.3 on 2025-06-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_bio_user_company_logo_user_company_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='otpverification',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='verification_type',
            field=models.CharField(choices=[('email', 'Email Verification'), ('phone', 'Phone Verification'), ('password_reset', 'Password Reset')], max_length=20),
        ),
    ]
