# Generated by Django 5.2.3 on 2025-07-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_otpverification_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='license_number',
        ),
        migrations.AddField(
            model_name='user',
            name='agreement_letter',
            field=models.FileField(blank=True, null=True, upload_to='agreement_letters/'),
        ),
    ]
