# Generated by Django 5.2.3 on 2026-01-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_license_number_user_agreement_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'SuperAdmin'), ('agencyadmin', 'AgencyAdmin'), ('franchisesadmin', 'FranchisesAdmin'), ('freelancer', 'Freelancer'), ('accountant', 'Accountant')], max_length=20),
        ),
    ]
