# Generated by Django 5.2.3 on 2025-06-27 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PosterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('Umrah', 'Umrah Template'), ('Hajj', 'Hajj Template'), ('Ramadan', 'Ramadan Template')], default='classic', max_length=20)),
                ('background_image', models.ImageField(upload_to='poster_templates/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackagePoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package_name', models.CharField(max_length=200)),
                ('package_type', models.CharField(choices=[('umrah_classic', 'Classic Umrah Package'), ('umrah_delux', 'Delux Umrah Package'), ('umrah_luxury', 'Luxury Umrah Package'), ('hajj_classic', 'Classic Hajj Package'), ('hajj_delux', 'Delux Hajj Package'), ('hajj_luxury', 'Luxury Hajj Package'), ('ramadan_early', 'Early Ramadan Package'), ('ramadan_laylat', 'Laylat al-Qadr Package'), ('ramadan_full', 'Full Month Ramadan Package')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('poster_jpg', models.ImageField(blank=True, null=True, upload_to='generated_posters/jpg/')),
                ('poster_png', models.ImageField(blank=True, null=True, upload_to='generated_posters/png/')),
                ('poster_pdf', models.FileField(blank=True, null=True, upload_to='generated_posters/pdf/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_posters', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poster_generator.postertemplate')),
            ],
            options={
                'permissions': [('can_create_poster', 'Can create poster')],
            },
        ),
    ]
