# Generated by Django 5.2.3 on 2025-06-23 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='sharing',
        ),
    ]
