# Generated by Django 5.2.3 on 2025-06-23 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_sharing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='package',
        ),
    ]
