# Generated by Django 5.2.3 on 2025-06-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_booking_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='travel_date',
        ),
        migrations.RemoveField(
            model_name='quickbooking',
            name='travel_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='travel_month',
            field=models.CharField(default='January', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quickbooking',
            name='travel_month',
            field=models.CharField(default='2025-07', max_length=8),
            preserve_default=False,
        ),
    ]
