# Generated by Django 5.2.3 on 2025-06-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_booking_travel_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickbooking',
            name='dues',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount due', max_digits=10),
        ),
        migrations.AddField(
            model_name='quickbooking',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount paid', max_digits=10),
        ),
    ]
