# Generated by Django 5.2.3 on 2025-06-22 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_number', models.CharField(max_length=20, unique=True)),
                ('applicant_name', models.CharField(max_length=255)),
                ('passport_number', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=100)),
                ('destination_country', models.CharField(max_length=100)),
                ('visa_type', models.CharField(choices=[('hajj', 'Hajj'), ('umrah', 'Umrah'), ('ramadan', 'Ramadan'), ('tourist', 'Tourist')], max_length=20)),
                ('travel_date', models.DateField()),
                ('return_date', models.DateField()),
                ('purpose_of_visit', models.TextField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('issued', 'Issued')], default='draft', max_length=20)),
                ('processing_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('embassy_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('can_process_application', 'Can process visa applications'), ('can_view_all_applications', 'Can view all visa applications')],
            },
        ),
        migrations.CreateModel(
            name='VisaDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('photo', 'Passport Photo'), ('invitation', 'Invitation Letter'), ('bank_statement', 'Bank Statement'), ('employment_letter', 'Employment Letter'), ('hotel_booking', 'Hotel Booking'), ('flight_booking', 'Flight Booking'), ('other', 'Other')], max_length=50)),
                ('document_file', models.FileField(upload_to='visa_documents/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
                ('visa_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='visa.visaapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
