# Generated by Django 5.2.3 on 2025-07-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0003_remove_visaapplication_embassy_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visaapplication',
            name='embassy_fee',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=22, max_digits=10),
            preserve_default=False,
        ),
    ]
